#!/usr/bin/env python3
"""Generate or update the Homebrew formula for endara-relay.

Renders Formula/endara-relay.rb from a fixed template using the provided
version and per-target SHA256 sums. Idempotent: writing the same inputs twice
produces the same file. Works for both create-from-scratch and in-place update.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

FORMULA_TEMPLATE = """\
# This file is auto-generated by endara-ai/endara-relay's release workflow.
# Manual edits will be overwritten on the next release.
class EndaraRelay < Formula
  desc "MCP server aggregator that connects multiple MCP servers behind a single endpoint"
  homepage "https://github.com/endara-ai/endara-relay"
  version "{version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{{version}}/endara-relay-v#{{version}}-aarch64-apple-darwin.tar.gz"
      sha256 "{sha_arm64_darwin}"
    end
    on_intel do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{{version}}/endara-relay-v#{{version}}-x86_64-apple-darwin.tar.gz"
      sha256 "{sha_x64_darwin}"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{{version}}/endara-relay-v#{{version}}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "{sha_arm64_linux}"
    end
    on_intel do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{{version}}/endara-relay-v#{{version}}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "{sha_x64_linux}"
    end
  end

  def install
    bin.install "endara-relay"
  end

  test do
    assert_match "endara-relay", shell_output("#{{bin}}/endara-relay --version")
  end
end
"""


def render(
    version: str,
    sha_arm64_darwin: str,
    sha_x64_darwin: str,
    sha_arm64_linux: str,
    sha_x64_linux: str,
) -> str:
    return FORMULA_TEMPLATE.format(
        version=version,
        sha_arm64_darwin=sha_arm64_darwin,
        sha_x64_darwin=sha_x64_darwin,
        sha_arm64_linux=sha_arm64_linux,
        sha_x64_linux=sha_x64_linux,
    )


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="Version without leading 'v', e.g. 0.1.1")
    parser.add_argument("--sha256-arm64-darwin", required=True, dest="sha_arm64_darwin")
    parser.add_argument("--sha256-x64-darwin", required=True, dest="sha_x64_darwin")
    parser.add_argument("--sha256-arm64-linux", required=True, dest="sha_arm64_linux")
    parser.add_argument("--sha256-x64-linux", required=True, dest="sha_x64_linux")
    parser.add_argument(
        "--formula-path",
        required=True,
        type=Path,
        help="Path to Formula/endara-relay.rb (created if missing).",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.version.startswith("v"):
        print(f"--version must not start with 'v' (got {args.version!r})", file=sys.stderr)
        return 2
    rendered = render(
        version=args.version,
        sha_arm64_darwin=args.sha_arm64_darwin,
        sha_x64_darwin=args.sha_x64_darwin,
        sha_arm64_linux=args.sha_arm64_linux,
        sha_x64_linux=args.sha_x64_linux,
    )
    formula_path: Path = args.formula_path
    formula_path.parent.mkdir(parents=True, exist_ok=True)
    existed = formula_path.exists()
    formula_path.write_text(rendered, encoding="utf-8")
    action = "Updated" if existed else "Created"
    print(f"{action} {formula_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

